# This is a basic workflow to help you get started with Actions

name: Publish Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2.3.2
      name: Checkout
    - name: Install package
      run: pip install .
    # Build documentation
    - uses: ammaraskar/sphinx-action@master
      name: Build docs
      with:
        build-command: "make github"
        docs-folder: "docsrc/"
    # Commit to gh-pages
    - name: Commit documentation changes
      run: |
        git clone https://github.com/chapinb/libvxshare.git --branch gh-pages --single-branch gh-pages
        cp -r docs/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
